development:
  adapter: postgresql
  encoding: unicode
  database: iulia_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: iulia_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  pool: 5